name = "Landfire"
uuid = "16f38fd6-0379-4569-89bb-2d3d56e50de8"
version = "0.0.1"
authors = ["Josh Day <emailjoshday@gmail.com> and contributors"]

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Downloads = "f43a241f-c20a-4ad4-852c-f6b1247861c6"
Extents = "411431e0-e8b7-467b-b5e0-f676ba4f2910"
GeoInterface = "cf35fbd7-0cd7-5166-be24-54bfbe79505f"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
StyledStrings = "f489334b-da3d-4c2e-b8f0-e476e12c162b"

[compat]
Dates = "1.11.0"
Downloads = "1.6.0"
Extents = "0.1.6"
GeoInterface = "1.6.0"
HTTP = "1"
JSON3 = "1"
StyledStrings = "1.11.0, 1"
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
